export interface EsmaItem {
  id: number;
  arabic: string;
  turkish: string;
  meaning: string;
}

export const ESMA_UL_HUSNA: EsmaItem[] = [
  { id: 1, arabic: 'الرَّحْمَنُ', turkish: 'Er-Rahman', meaning: 'Esirgeyen, bütün yaratılmışlara merhamet eden' },
  { id: 2, arabic: 'الرَّحِيمُ', turkish: 'Er-Rahim', meaning: 'Bağışlayan, müminlere merhamet eden' },
  { id: 3, arabic: 'الْمَلِكُ', turkish: 'El-Melik', meaning: 'Mülkün sahibi, her şeyin hükümdarı' },
  { id: 4, arabic: 'الْقُدُّوسُ', turkish: 'El-Kuddüs', meaning: 'Her türlü eksiklikten uzak, tertemiz' },
  { id: 5, arabic: 'السَّلاَمُ', turkish: 'Es-Selam', meaning: 'Selamet veren, esenlik kaynağı' },
  { id: 6, arabic: 'الْمُؤْمِنُ', turkish: 'El-Mü\'min', meaning: 'Güven veren, iman nurunu veren' },
  { id: 7, arabic: 'الْمُهَيْمِنُ', turkish: 'El-Müheymin', meaning: 'Gözetip koruyan' },
  { id: 8, arabic: 'الْعَزِيزُ', turkish: 'El-Aziz', meaning: 'Güçlü, yenilmez, her şeye galip' },
  { id: 9, arabic: 'الْجَبَّارُ', turkish: 'El-Cebbar', meaning: 'İstediğini mutlaka yapan, düzelten' },
  { id: 10, arabic: 'الْمُتَكَبِّرُ', turkish: 'El-Mütekebbir', meaning: 'Büyüklükte eşi olmayan' },
  { id: 11, arabic: 'الْخَالِقُ', turkish: 'El-Halik', meaning: 'Yaratan, yoktan var eden' },
  { id: 12, arabic: 'الْبَارِئُ', turkish: 'El-Bari', meaning: 'Her şeyi kusursuz yaratan' },
  { id: 13, arabic: 'الْمُصَوِّرُ', turkish: 'El-Musavvir', meaning: 'Her şeye şekil veren' },
  { id: 14, arabic: 'الْغَفَّارُ', turkish: 'El-Gaffar', meaning: 'Günahları çokça bağışlayan' },
  { id: 15, arabic: 'الْقَهَّارُ', turkish: 'El-Kahhar', meaning: 'Her şeye galip gelen' },
  { id: 16, arabic: 'الْوَهَّابُ', turkish: 'El-Vehhab', meaning: 'Karşılıksız bol bol veren' },
  { id: 17, arabic: 'الرَّزَّاقُ', turkish: 'Er-Rezzak', meaning: 'Rızık veren' },
  { id: 18, arabic: 'الْفَتَّاحُ', turkish: 'El-Fettah', meaning: 'Her türlü zorluğu açan' },
  { id: 19, arabic: 'اَلْعَلِيمُ', turkish: 'El-Alim', meaning: 'Her şeyi bilen' },
  { id: 20, arabic: 'الْقَابِضُ', turkish: 'El-Kabıd', meaning: 'Daraltan, sıkan' },
  { id: 21, arabic: 'الْبَاسِطُ', turkish: 'El-Basıt', meaning: 'Genişleten, açan' },
  { id: 22, arabic: 'الْخَافِضُ', turkish: 'El-Hafıd', meaning: 'Alçaltan' },
  { id: 23, arabic: 'الرَّافِعُ', turkish: 'Er-Rafi', meaning: 'Yükselten' },
  { id: 24, arabic: 'الْمُعِزُّ', turkish: 'El-Muiz', meaning: 'İzzet ve şeref veren' },
  { id: 25, arabic: 'المُذِلُّ', turkish: 'El-Müzil', meaning: 'Zillete düşüren' },
  { id: 26, arabic: 'السَّمِيعُ', turkish: 'Es-Semi', meaning: 'Her şeyi işiten' },
  { id: 27, arabic: 'الْبَصِيرُ', turkish: 'El-Basir', meaning: 'Her şeyi gören' },
  { id: 28, arabic: 'الْحَكَمُ', turkish: 'El-Hakem', meaning: 'Hükmeden, haklıyı haksızdan ayıran' },
  { id: 29, arabic: 'الْعَدْلُ', turkish: 'El-Adl', meaning: 'Mutlak adil' },
  { id: 30, arabic: 'اللَّطِيفُ', turkish: 'El-Latif', meaning: 'Lütuf ve ihsan sahibi' },
  { id: 31, arabic: 'الْخَبِيرُ', turkish: 'El-Habir', meaning: 'Her şeyden haberdar' },
  { id: 32, arabic: 'الْحَلِيمُ', turkish: 'El-Halim', meaning: 'Yumuşak davranan, ceza vermede acele etmeyen' },
  { id: 33, arabic: 'الْعَظِيمُ', turkish: 'El-Azim', meaning: 'Büyüklükte sınırsız' },
  { id: 34, arabic: 'الْغَفُورُ', turkish: 'El-Gafur', meaning: 'Affı çok olan' },
  { id: 35, arabic: 'الشَّكُورُ', turkish: 'Eş-Şekür', meaning: 'Az iyiliğe çok mükafat veren' },
  { id: 36, arabic: 'الْعَلِيُّ', turkish: 'El-Aliyy', meaning: 'Yüceler yücesi' },
  { id: 37, arabic: 'الْكَبِيرُ', turkish: 'El-Kebir', meaning: 'Büyüklükte eşsiz' },
  { id: 38, arabic: 'الْحَفِيظُ', turkish: 'El-Hafiz', meaning: 'Koruyup gözeten' },
  { id: 39, arabic: 'المُقِيتُ', turkish: 'El-Mukit', meaning: 'Her yaratığın azığını veren' },
  { id: 40, arabic: 'الْحسِيبُ', turkish: 'El-Hasib', meaning: 'Hesaba çeken' },
  { id: 41, arabic: 'الْجَلِيلُ', turkish: 'El-Celil', meaning: 'Celal ve azamet sahibi' },
  { id: 42, arabic: 'الْكَرِيمُ', turkish: 'El-Kerim', meaning: 'Cömert, kerem sahibi' },
  { id: 43, arabic: 'الرَّقِيبُ', turkish: 'Er-Rakib', meaning: 'Her şeyi gözetleyen' },
  { id: 44, arabic: 'الْمُجِيبُ', turkish: 'El-Mücib', meaning: 'Duaları kabul eden' },
  { id: 45, arabic: 'الْوَاسِعُ', turkish: 'El-Vasi', meaning: 'Rahmeti geniş olan' },
  { id: 46, arabic: 'الْحَكِيمُ', turkish: 'El-Hakim', meaning: 'Hikmet sahibi' },
  { id: 47, arabic: 'الْوَدُودُ', turkish: 'El-Vedüd', meaning: 'Seven, sevilen' },
  { id: 48, arabic: 'الْمَجِيدُ', turkish: 'El-Mecid', meaning: 'Şanı büyük, şerefli' },
  { id: 49, arabic: 'الْبَاعِثُ', turkish: 'El-Bais', meaning: 'Ölüleri dirilten' },
  { id: 50, arabic: 'الشَّهِيدُ', turkish: 'Eş-Şehid', meaning: 'Her şeye şahit olan' },
  { id: 51, arabic: 'الْحَقُّ', turkish: 'El-Hakk', meaning: 'Varlığı hakiki olan' },
  { id: 52, arabic: 'الْوَكِيلُ', turkish: 'El-Vekil', meaning: 'Her şeye vekil olan' },
  { id: 53, arabic: 'الْقَوِيُّ', turkish: 'El-Kaviyy', meaning: 'Güçlü' },
  { id: 54, arabic: 'الْمَتِينُ', turkish: 'El-Metin', meaning: 'Kuvveti sarsılmaz' },
  { id: 55, arabic: 'الْوَلِيُّ', turkish: 'El-Veliyy', meaning: 'Müminlerin dostu' },
  { id: 56, arabic: 'الْحَمِيدُ', turkish: 'El-Hamid', meaning: 'Övülmeye layık' },
  { id: 57, arabic: 'الْمُحْصِي', turkish: 'El-Muhsi', meaning: 'Her şeyi sayan' },
  { id: 58, arabic: 'الْمُبْدِئُ', turkish: 'El-Mübdi', meaning: 'Yoktan var eden' },
  { id: 59, arabic: 'الْمُعِيدُ', turkish: 'El-Muid', meaning: 'Yeniden yaratan' },
  { id: 60, arabic: 'الْمُحْيِي', turkish: 'El-Muhyi', meaning: 'Hayat veren' },
  { id: 61, arabic: 'اَلْمُمِيتُ', turkish: 'El-Mümit', meaning: 'Öldüren' },
  { id: 62, arabic: 'الْحَيُّ', turkish: 'El-Hayy', meaning: 'Diri, her şeyi bilen' },
  { id: 63, arabic: 'الْقَيُّومُ', turkish: 'El-Kayyum', meaning: 'Her şeyi ayakta tutan' },
  { id: 64, arabic: 'الْوَاجِدُ', turkish: 'El-Vacid', meaning: 'İstediğini bulan' },
  { id: 65, arabic: 'الْمَاجِدُ', turkish: 'El-Macid', meaning: 'Kadri büyük' },
  { id: 66, arabic: 'الْواحِدُ', turkish: 'El-Vahid', meaning: 'Tek olan' },
  { id: 67, arabic: 'اَلاَحَدُ', turkish: 'El-Ehad', meaning: 'Bir olan' },
  { id: 68, arabic: 'الصَّمَدُ', turkish: 'Es-Samed', meaning: 'Hiçbir şeye muhtaç olmayan' },
  { id: 69, arabic: 'الْقَادِرُ', turkish: 'El-Kadir', meaning: 'Her şeye gücü yeten' },
  { id: 70, arabic: 'الْمُقْتَدِرُ', turkish: 'El-Muktedir', meaning: 'Kudret sahiplerini yaratan' },
  { id: 71, arabic: 'الْمُقَدِّمُ', turkish: 'El-Mukaddim', meaning: 'Öne alan' },
  { id: 72, arabic: 'الْمُؤَخِّرُ', turkish: 'El-Muahhir', meaning: 'Arkaya bırakan' },
  { id: 73, arabic: 'الأوَّلُ', turkish: 'El-Evvel', meaning: 'İlk, başlangıcı olmayan' },
  { id: 74, arabic: 'الآخِرُ', turkish: 'El-Ahir', meaning: 'Son, sonu olmayan' },
  { id: 75, arabic: 'الظَّاهِرُ', turkish: 'Ez-Zahir', meaning: 'Varlığı aşikar olan' },
  { id: 76, arabic: 'الْبَاطِنُ', turkish: 'El-Batın', meaning: 'Gizli, akıl ile idrak edilemeyen' },
  { id: 77, arabic: 'الْوَالِي', turkish: 'El-Vali', meaning: 'Kainatı idare eden' },
  { id: 78, arabic: 'الْمُتَعَالِي', turkish: 'El-Müteali', meaning: 'Yüce' },
  { id: 79, arabic: 'الْبَرُّ', turkish: 'El-Berr', meaning: 'İyilik ve ihsan sahibi' },
  { id: 80, arabic: 'التَّوَابُ', turkish: 'Et-Tevvab', meaning: 'Tövbeleri kabul eden' },
  { id: 81, arabic: 'الْمُنْتَقِمُ', turkish: 'El-Müntakim', meaning: 'Suçluları cezalandıran' },
  { id: 82, arabic: 'الْعَفُوُّ', turkish: 'El-Afüvv', meaning: 'Affı çok olan' },
  { id: 83, arabic: 'الرَّؤُوفُ', turkish: 'Er-Raüf', meaning: 'Çok merhametli' },
  { id: 84, arabic: 'مَالِكُ الْمُلْكِ', turkish: 'Malik-ül Mülk', meaning: 'Mülkün ebedi sahibi' },
  { id: 85, arabic: 'ذُوالْجَلاَلِ وَالإكْرَامِ', turkish: 'Zül-Celali vel-İkram', meaning: 'Celal ve ikram sahibi' },
  { id: 86, arabic: 'الْمُقْسِطُ', turkish: 'El-Muksit', meaning: 'Adaletli' },
  { id: 87, arabic: 'الْجَامِعُ', turkish: 'El-Cami', meaning: 'Toplayan, bir araya getiren' },
  { id: 88, arabic: 'الْغَنِيُّ', turkish: 'El-Ganiyy', meaning: 'Zengin, hiçbir şeye muhtaç olmayan' },
  { id: 89, arabic: 'الْمُغْنِي', turkish: 'El-Mugni', meaning: 'Zenginlik veren' },
  { id: 90, arabic: 'اَلْمَانِعُ', turkish: 'El-Mani', meaning: 'Engelleyen, koruyan' },
  { id: 91, arabic: 'الضَّارَّ', turkish: 'Ed-Darr', meaning: 'Zarar vereni yaratan' },
  { id: 92, arabic: 'النَّافِعُ', turkish: 'En-Nafi', meaning: 'Fayda vereni yaratan' },
  { id: 93, arabic: 'النُّورُ', turkish: 'En-Nur', meaning: 'Alemleri nurlandıran' },
  { id: 94, arabic: 'الْهَادِي', turkish: 'El-Hadi', meaning: 'Hidayete erdiren' },
  { id: 95, arabic: 'الْبَدِيعُ', turkish: 'El-Bedi', meaning: 'Eşsiz yaratan' },
  { id: 96, arabic: 'اَلْبَاقِي', turkish: 'El-Baki', meaning: 'Varlığının sonu olmayan' },
  { id: 97, arabic: 'الْوَارِثُ', turkish: 'El-Varis', meaning: 'Her şeyin gerçek sahibi' },
  { id: 98, arabic: 'الرَّشِيدُ', turkish: 'Er-Reşid', meaning: 'Doğru yolu gösteren' },
  { id: 99, arabic: 'الصَّبُورُ', turkish: 'Es-Sabür', meaning: 'Çok sabırlı' },
];
